### PR TITLE
Update 20347A_LAB_04.md

### PR DESCRIPTION
**Pull request by Pascal-KOTTE**
I was getting the error, "inbound synchronization rule Object reference not set instance", and loose some time to find why !! Why not a clear message Tag is mandatory $#@¢%&§! SO I propose to add this line into task 4 the Exercise 2: Configuring directory synchronization

https://github.com/MicrosoftLearning/20347-Enabling-and-Managing-Office365/blob/master/Instructions/20347A_LAB_04.md#task-4-configure-synchronization-service-filtering-for-object-attribute

### CODE REVIEW

**Comment by JasonHershey** [comment]
@Pascal-KOTTE Did you try the alternative version of the procedure that appears as a note?   this problem was first noted in issue #46 though we didn't see your proposed fix about adding Tag value.  We were actually thinking this may be a bug in AAD Connect because its a new issue, and I'm routing may way through MS channels to see if that is the case.  But, you've given some new info for the report to MS.

**Comment by JasonHershey** [comment]
Going ahead and rejecting these changes at this time.  I am working on some other updates to this procedure since its gotten out-of-date with the current o365 UI

**Comment by itbland** [comment]
Update: I ran this lab today in class and was able to create a new rule normally.
AD Connect version 1.1.614.0, released 9/5/2017 (the current download)
[Azure AD Connect: Version release history](https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-version-history)

**Comment by Pascal-KOTTE** [comment]
tanks

**Pull request closed without merging**
